from __future__ import annotations

import pytest

import nonebot_plugin_akito.features.random_paro as random_paro
import nonebot_plugin_akito.features.random_paro_render as random_paro_render


def test_page_width_values_from_builders():
    today = random_paro._today_str()
    group_stats = random_paro._new_group_stats(today)
    period_stats = random_paro._new_period_stats(date=today)
    user_stats = random_paro._new_user_stats()
    egg_history = random_paro._new_user_egg_history()

    rank_data = random_paro._build_paro_rank_page_data_from_stats(group_stats, period_stats, "daily")
    cook_data = random_paro._build_egg_rank_page_data_from_stats(group_stats, period_stats, "history")
    profile_data = random_paro._build_personal_paro_page_data_from_user_stats("42", "Tester", user_stats, egg_history)
    draw_data = random_paro._build_draw_result_page_data([("Akito", "Toya", False, None)], remaining=2, nickname="Tester")

    assert rank_data["page_width"] == 680
    assert cook_data["page_width"] == 680
    assert profile_data["page_width"] == 680
    assert draw_data["page_width"] == 620


@pytest.mark.asyncio
async def test_render_random_paro_page_uses_page_width_for_viewport(monkeypatch):
    captured: dict[str, object] = {}

    async def fake_html_to_pic(html: str, *, viewport: dict, type: str, quality: int) -> bytes:
        captured["html"] = html
        captured["viewport"] = viewport
        captured["type"] = type
        captured["quality"] = quality
        return b"ok"

    monkeypatch.setattr(random_paro_render, "html_to_pic", fake_html_to_pic)

    result = await random_paro_render.render_random_paro_page(
        "base.html",
        {"title": "Test", "page_width": 620},
    )

    assert result == b"ok"
    assert captured["viewport"] == {"width": 620, "height": 100}
    assert captured["type"] == "jpeg"
    assert captured["quality"] == 80


def test_base_template_centers_footer_when_footer_right_empty():
    html = random_paro_render._TEMPLATE_ENV.get_template("base.html").render(
        title="Test",
        footer_right="",
    )

    assert '<div class="foot center">' in html
    assert html.count("<span>") == 1
    assert "Generated by AkitoBot" in html


def test_base_template_keeps_two_column_footer_when_footer_right_present():
    html = random_paro_render._TEMPLATE_ENV.get_template("base.html").render(
        title="Test",
        footer_right="2026-06-11 22:00",
    )

    assert '<div class="foot">' in html
    assert '<div class="foot center">' not in html
    assert html.count("<span>") == 2
    assert "2026-06-11 22:00" in html


def test_draw_result_template_uses_150px_pair_tiles():
    template_text = (random_paro_render.TEMPLATE_DIR / "draw_result.html").read_text(encoding="utf-8")

    assert ".tile {" in template_text
    assert "width: 150px;" in template_text
    assert "height: 150px;" in template_text
